# Generated by Django 5.2 on 2025-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_user_alter_subscription_subscriber"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
