name: blog-platform

services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: blog-platform-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis Cache & Sessions
  redis:
    image: redis:7-alpine
    container_name: blog-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
