# Generated by Django 5.2 on 2025-05-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletin",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
