# Generated by Django 5.2 on 2025-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_subscribed_to_platform",
            field=models.BooleanField(default=True),
        ),
    ]
