# Generated by Django 5.2 on 2025-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_auto_subscribed_to_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default_avatar.jpg", upload_to="static/images"
            ),
        ),
    ]
