# Generated by Django 5.2 on 2025-07-15 21:08

import sys
from django.db import migrations, models

# Only import cloudinary for non-test environments
if 'test' not in sys.argv:
    import cloudinary_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_auto_subscribed_to_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default_avatar.png",
                storage=cloudinary_storage.storage.MediaCloudinaryStorage() if 'test' not in sys.argv else None,
                upload_to="profile_pics/",
            ),
        ),
    ]
