# Generated by Django 5.2 on 2025-07-15 21:08

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_auto_subscribed_to_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="default_avatar.png",
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                upload_to="profile_pics/",
            ),
        ),
    ]
