# Generated by Django 5.2 on 2025-11-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_avatar'),
        ('content', '0010_alter_article_title_alter_article_unique_together'),
        ('engagement', '0003_readlater'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='readlater',
            unique_together={('author', 'article')},
        ),
    ]
