# Generated by Django 5.2 on 2025-11-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_avatar'),
        ('content', '0010_alter_article_title_alter_article_unique_together'),
        ('engagement', '0004_alter_comment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article'], name='engagement__article_4e6718_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='engagement__author__4c1e44_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['article'], name='engagement__article_57c58f_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['author'], name='engagement__author__b5924a_idx'),
        ),
        migrations.AddIndex(
            model_name='readlater',
            index=models.Index(fields=['article'], name='engagement__article_33b9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='readlater',
            index=models.Index(fields=['author'], name='engagement__author__d6358d_idx'),
        ),
    ]
