# Generated by Django 5.2 on 2026-02-16 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_avatar'),
        ('content', '0011_article_slug_alter_article_visibility'),
        ('engagement', '0005_comment_engagement__article_4e6718_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='content.article'),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='readlater',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='content.article'),
        ),
        migrations.AlterField(
            model_name='readlater',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='accounts.profile'),
        ),
    ]
