# Generated by Django 5.2 on 2025-04-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created"], "verbose_name_plural": "Članky"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Kategorie"},
        ),
    ]
