# Generated by Django 5.2 on 2025-05-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_article_evaluation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="subtite",
            new_name="subtitle",
        ),
        migrations.AlterField(
            model_name="article",
            name="evaluation",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "visibility", "evaluation"],
                name="content_art_status_65fae9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["bulletin", "status"], name="content_art_bulleti_8b376f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["evaluation", "created"], name="content_art_evaluat_fa032c_idx"
            ),
        ),
    ]
