# Generated by Django 5.2 on 2025-07-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_rename_subtite_article_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulletin",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="bulletin",
            name="is_platform_docs",
            field=models.BooleanField(default=False),
        ),
    ]
